### ISSUE TITLE
Emojis with mixed skin tone variants not rendering correctly

### ISSUE THREAD

**Issue by joeattardi** [joeattardi/picmo#188]
The latest emoji updates support handshake emojis with mixed skin tone variants. This is not rendering/working correctly currently.

When selecting the handshake, all the "half handshake" variants appear in the popup:

<img width="381" alt="image" src="https://user-images.githubusercontent.com/219285/163591803-5d4879e3-4c28-4bff-a9cd-ab455bcbdefd.png">

If one is selected, it renders two emojis side by side in the emitted result:

<img width="108" alt="image" src="https://user-images.githubusercontent.com/219285/163592021-c8d5511e-17d0-497e-91df-3f2eb84e84f2.png">

This is similar to the couple emojis ("with heart", "kissing", etc.):

<img width="384" alt="image" src="https://user-images.githubusercontent.com/219285/163592227-e4f49801-e6a0-4375-b0cc-0ea2c58ad2fb.png">

This one overflows in the preview area:

<img width="392" alt="image" src="https://user-images.githubusercontent.com/219285/163592320-bac174df-f42a-43bb-a9b8-6dfdb5ac8b24.png">

Apple has a nice interface for these types of emojis:

![handshake](https://user-images.githubusercontent.com/219285/163592624-d4daf732-5c51-4963-a58c-6c1d11c748e4.gif)

You can select the generic yellow one in the bottom left, or to construct a mixed one, the top row shows the left hand variants and the bottom row shows the right. You can click in each row to set the skin tone of each side, then click the final emoji in the bottom right.

## Tasks

- [ ] Find a way to identify such mixed variant emojis
- [ ] Provide the alternative variant popup for these
- [ ] If variant popup not used, make sure the weird double rendering issue shown above does not happen --> use the generic yellow one.

**Comment by joeattardi** [comment]
Some more details:

The variants exposed by the emoji data appear to be the two "halves":

<img width="106" alt="image" src="https://user-images.githubusercontent.com/219285/163593106-a94d37bc-4e31-4cfa-ac54-181ecf15fc7b.png">

Once the correct variant is chosen, the two glyphs need to be superimposed on top of each other.

**Comment by joeattardi** [comment]
Twemoji seems to handle this already:

<img width="374" alt="image" src="https://user-images.githubusercontent.com/219285/163593249-530e1615-7207-49a7-ae6b-68cdec37e2d0.png">

**Comment by joeattardi** [comment]
The mixed tone handshake is part of Emoji 14, this looks to be a rendering error for the OS not supporting it yet. It renders the emoji character sequence the only way it knows how.

Looking at the emojibase data, it looks like each variant also has a version field, so we can filter out unsupported variants to prevent the rendering issues.

**Comment by joeattardi** [comment]
Update: Even with Emoji 14 support, these are still not rendering correctly in some browsers. They look ok in Safari:

<img width="78" alt="image" src="https://user-images.githubusercontent.com/219285/163658130-796930a4-8116-42d4-913b-58ab247fd787.png">

But render incorrectly in Chrome:

<img width="106" alt="image" src="https://user-images.githubusercontent.com/219285/163658163-fe02112e-3759-4f46-971f-59110f7fc535.png">

Chrome bug here: https://bugs.chromium.org/p/chromium/issues/detail?id=1310282&q=emoji&can=2

**Comment by joeattardi** [comment]
Emoji variants with a version are filtered out when they don't match the current version. As for rendering issues, there's not much else that can be done if it's a browser bug other than provide a note in the documentation.

Closing this for now.
